services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db

  db:
    image: postgres:14
    env_file:
      - .env.local
    volumes:
      - ./src/app/lib/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
